# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `cssbundling-rails` gem.
# Please instead update this file by running `bin/tapioca gem cssbundling-rails`.

# typed: strict

module Cssbundling; end
class Cssbundling::Engine < ::Rails::Engine; end
Cssbundling::VERSION = T.let(T.unsafe(nil), String)
