# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `esbuild-rails` gem.
# Please instead update this file by running `bin/tapioca gem esbuild-rails`.

# typed: strict

module Esbuild; end
class Esbuild::Engine < ::Rails::Engine; end
Esbuild::VERSION = T.let(T.unsafe(nil), String)
