# https://connorshea.gitlab.io/blog/how-i-write-and-maintain-type-sigs-in-my-rails-app-with-sorbet.html
namespace :sorbet do
  namespace :update do
    desc 'Update Sorbet and Sorbet Rails RBIs.'
    task all: :environment do
      Bundler.with_unbundled_env do
        system('bundle exec tapioca gem')
        system('bundle exec tapioca dsl')

        # Generate a TODO RBI for constants Tapioca doesn't understand.
        system('bundle exec tapioca todo')

        # Run suggest-typed to increase/decrease the type level of files
        # as-necessary (for example, if types became more strict in an
        # autogenerated RBI this may cause Sorbet to downgrade the `typed:`
        # sigil for one of your files to `false`). Ensures that our code will
        # pass type checking regardless of any changes to the autogenerated
        # RBIs.
        system('bundle exec spoom bump')
      end
    end
  end
end
