# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ExportToFileJob`.
# Please instead update this file by running `bin/tapioca dsl ExportToFileJob`.

class ExportToFileJob
  class << self
    sig { params(args: T.untyped).returns(T.any(ExportToFileJob, FalseClass)) }
    def perform_later(*args); end

    sig { params(args: T.untyped).returns(T.untyped) }
    def perform_now(*args); end
  end
end
